[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "insighta"
version = "0.1.0"
dependencies = [
    "typer",
    "rich",
    "httpx",
    "keyring"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff"
]

[project.scripts]
insighta = "insighta.main:app"